# Generated by Django 5.1.4 on 2026-08-23 19:15

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catastro', '0000_postgis_y_srid'),    
]

    operations = [
        migrations.CreateModel(
            name='Predio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_predial', models.CharField(db_index=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^\\d{30}$', 'El número predial nacional debe tener 30 dígitos.')], verbose_name='Número predial nacional')),
                ('nombre_direccion', models.CharField(max_length=255, verbose_name='Nombre o dirección')),
                ('condicion_predio', models.CharField(choices=[('PH', 'Propiedad Horizontal'), ('NPH', 'No Propiedad Horizontal'), ('CONDOMINIO', 'Condominio'), ('INFORMAL', 'Informal')], db_index=True, max_length=20, verbose_name='Condición del predio')),
                ('poligono', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Linderos del predio')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Predio',
                'verbose_name_plural': 'Predios',
                'ordering': ['numero_predial'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Documento de identidad')),
                ('nombre_completo', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='ZonaRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('nivel_riesgo', models.CharField(choices=[('ALTO', 'Alto'), ('MEDIO', 'Medio'), ('BAJO', 'Bajo')], db_index=True, max_length=10, verbose_name='Nivel de riesgo')),
                ('poligono', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Área de la zona de riesgo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona de riesgo',
                'verbose_name_plural': 'Zonas de riesgo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Copropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Porcentaje de participación')),
                ('predio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copropiedades', to='catastro.predio')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copropiedades', to='catastro.propietario')),
            ],
            options={
                'verbose_name': 'Copropiedad',
                'verbose_name_plural': 'Copropiedades',
            },
        ),
        migrations.AddField(
            model_name='predio',
            name='copropietarios',
            field=models.ManyToManyField(blank=True, related_name='predios_en_copropiedad', through='catastro.Copropiedad', to='catastro.propietario'),
        ),
        migrations.AddField(
            model_name='predio',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predios', to='catastro.propietario', verbose_name='Propietario principal'),
        ),
        migrations.AddConstraint(
            model_name='copropiedad',
            constraint=models.UniqueConstraint(fields=('predio', 'propietario'), name='uq_copropiedad_predio_propietario'),
        ),
    ]
